channels:
  - conda-forge
dependencies:
  - python==3.8
  - pip:
    - nbsphinx
    - jupyter-sphinx
    - sphinx_rtd_theme
    - periodictable
    - pandoc
    - scipy
    - numpy
    - sphinx
    - pandas
    - numpydoc
    - setuptools
    - cython
    - jupyter
    - matplotlib
